### ISSUE TITLE
Why renameFiles function is needed?

### ISSUE THREAD

**Issue by cawa-93** [ci010/electron-vue-next#6]
I do not understand why this function is needed.

https://github.com/ci010/electron-vue-next/blob/a304825fac4dd32609a69ce35aab661de1673c3b/scripts/build.js#L64-L72

I tried to comment on it and nothing broke. On the contrary. I had received an error before:
```
Build electron
  • electron-builder  version=22.9.1 os=10.0.19042
....

Error: dest already exists.
    at C:\Users\kozac\Dev\electron-vue-next\node_modules\fs-extra\lib\move\move.js:41:31
    at C:\Users\kozac\Dev\electron-vue-next\node_modules\universalify\index.js:23:46
```
But removing the file renaming fixed the error.

**Comment by ci010** [comment]
The `electron-builder` build the `latest.yml` with the url replacing the ` ` (space) into `-` . 

```yml
version: 0.0.0
files:
  - url: electron-vue-next-Setup-0.0.0.exe
    sha512: GXn5QdYUBhCTDyzohkzo0LE+qxKeJH6OQXL8J/TX3c6wmCG7c+JaZLsOpTfYHx4BnP1V/K9JCUulZeO24XDiig==
    size: 54854767
path: electron-vue-next-Setup-0.0.0.exe
sha512: GXn5QdYUBhCTDyzohkzo0LE+qxKeJH6OQXL8J/TX3c6wmCG7c+JaZLsOpTfYHx4BnP1V/K9JCUulZeO24XDiig==
releaseDate: '2020-11-08T04:19:43.773Z'
```

And if it uploads to github it will not replace the ` ` (space) into `-`. So the `latest.yml` url will mismatch.

Current move code has bug... I just fix it in [3dcf0fd7d9146fea0f217278ad411e2d57d0bbe7](https://github.com/ci010/electron-vue-next/commit/3dcf0fd7d9146fea0f217278ad411e2d57d0bbe7).
